spring:
  application:
    name: dc-alfa-bank-service
application:
  alfa-bank:
    url: http://localhost:9090/calculateFee
    username: alfaany
    password: gh1TG2d(5V-
  proxy:
    host: 172.28.8.120
    port: 8080
    username: Tech_Linux_Repo
    password: 8CNrnd_Agl
    enabled: false