spring:
  application:
    name: dc-alfa-bank-service
application:
  alfa-bank:
    url: https://195.47.220.55:8443/AnyToCardService.svc?singleWsdl
    username: alfaany
    password: gh1TG2d(5V-
  proxy:
    host: 172.28.8.120
    port: 3128
    username: Tech_Linux_Repo
    password: 8CNrnd_Agl
    enabled: true